name: Build Nuclei OpenOCD

on:
  push:
    branches: [ xpack-nuclei* ]
  pull_request:
    branches: [ xpack-nuclei* ]

jobs:
  build-release:
    name: build release version on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
    env: 
      CC: gcc-8
      CXX: g++-8

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Preload docker images
      run: |
        # Remove --tty in script to try to avoid error: the input device is not a TTY
        # No need for non-ci run
        find scripts/ -type f | xargs sed -i -e 's/--tty/ /g'
        bash ./scripts/build.sh preload-images
    - name: Build nuclei openocd
      run: |
        export COMPOSE_INTERACTIVE_NO_CLI=1
        bash ./scripts/build.sh --all
    - name: Archive nuclei openocd
      run: |
        OPENOCD_DEPLOY=$(readlink -f $HOME/Work/openocd-*/deploy)
        WORKPWD=$(pwd)
        cd $OPENOCD_DEPLOY
        zip -9 -q -r ${WORKPWD}/nuclei_openocd.zip .
    - name: Upload openocd artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: nuclei_openocd_release
        # A file, directory or wildcard pattern that describes what to upload
        path: nuclei_openocd.zip

  build-develop:
    name: build develop version on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
    env: 
      CC: gcc-8
      CXX: g++-8

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Preload docker images
      run: |
        # Remove --tty in script to try to avoid error: the input device is not a TTY
        # No need for non-ci run
        find scripts/ -type f | xargs sed -i -e 's/--tty/ /g'
        bash ./scripts/build.sh preload-images
        # Change version to develop
        echo "develop" > ./scripts/VERSION
    - name: Build nuclei openocd
      run: |
        export COMPOSE_INTERACTIVE_NO_CLI=1
        bash ./scripts/build.sh --all
    - name: Archive nuclei openocd
      run: |
        OPENOCD_DEPLOY=$(readlink -f $HOME/Work/openocd-*/deploy)
        WORKPWD=$(pwd)
        cd $OPENOCD_DEPLOY
        zip -9 -q -r ${WORKPWD}/nuclei_openocd.zip .
    - name: Upload openocd artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: nuclei_openocd_develop
        # A file, directory or wildcard pattern that describes what to upload
        path: nuclei_openocd.zip